name: CI

on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main 

jobs:
  run-tests:
    name: ci_jobs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Requirements
      run: make requirements

    - name: Dev setup
      run: make dev-setup

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

    - name: check pip-audit
      run: which pip-audit

    - name: Run checks
      run: make run-checks

        
       
  deploy-terraform:
    name: deploy-terraform
    environment: dev
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.DEPLOY_USER_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEPLOY_USER_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        working-directory: terraform
        run: terraform init
      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan
        env:
          TF_VAR_pg_host: ${{ secrets.TF_VAR_PG_HOST }}
          TF_VAR_pg_port: ${{ secrets.TF_VAR_PG_PORT }}
          TF_VAR_pg_user: ${{ secrets.TF_VAR_PG_USER }}
          TF_VAR_pg_database: ${{ secrets.TF_VAR_PG_DATABASE }}
          TF_VAR_pg_password: ${{ secrets.TF_VAR_PG_PASSWORD }}
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve
        env:
          TF_VAR_pg_host: ${{ secrets.TF_VAR_PG_HOST }}
          TF_VAR_pg_port: ${{ secrets.TF_VAR_PG_PORT }}
          TF_VAR_pg_user: ${{ secrets.TF_VAR_PG_USER }}
          TF_VAR_pg_database: ${{ secrets.TF_VAR_PG_DATABASE }}
          TF_VAR_pg_password: ${{ secrets.TF_VAR_PG_PASSWORD }}
